spring:
  application:
    name: st-microservice-ili
  servlet:
    multipart:
      maxFileSize: 250MB
      maxRequestSize: 250MB
  main:
    allow-bean-definition-overriding: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate.ddl-auto: create
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9005
  tomcat:
    max-threads: 0

iliProcesses:
  srs: "9377"

st:
  rabbitmq:
    queueInstance: st.queue.ili